### PR TITLE
New Updates

### PR DESCRIPTION
**Pull request by jugrajsingh**

### CODE REVIEW

**Comment by amarjeetkapoor1** [comment]
@jugrajsingh ,Please remove the merge conflict.

**Comment by amarjeetkapoor1** [comment]
App crashes on sharing location problem is with the app permissions. It doesn't asks for permissions explicitly.

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: in.gndec.sunehag, PID: 17309
                  java.lang.IllegalArgumentException: Unknown permission: android.permission-group.LOCATION
                      at android.os.Parcel.readException(Parcel.java:1624)
                      at android.os.Parcel.readException(Parcel.java:1573)
                      at android.content.pm.IPackageManager$Stub$Proxy.shouldShowRequestPermissionRationale(IPackageManager.java:2764)
                      at android.app.ApplicationPackageManager.shouldShowRequestPermissionRationale(ApplicationPackageManager.java:522)
                      at android.app.Activity.shouldShowRequestPermissionRationale(Activity.java:3923)
                      at android.support.v4.app.ActivityCompatApi23.shouldShowRequestPermissionRationale(ActivityCompatApi23.java:50)
                      at android.support.v4.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:419)
                      at in.gndec.sunehag.ui.ConversationActivity$6.onPresenceSelected(ConversationActivity.java:521)
                      at in.gndec.sunehag.ui.ConversationActivity.selectPresenceToAttachFile(ConversationActivity.java:548)
                      at in.gndec.sunehag.ui.ConversationActivity.attachFile(ConversationActivity.java:642)
                      at in.gndec.sunehag.ui.ConversationActivity$10.onMenuItemClick(ConversationActivity.java:827)
                      at android.widget.PopupMenu.onMenuItemSelected(PopupMenu.java:252)
                      at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
                      at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
                      at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
                      at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
                      at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:200)
                      at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                      at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
                      at android.widget.AbsListView$PerformClick.run(AbsListView.java:3081)
                      at android.widget.AbsListView$3.run(AbsListView.java:3947)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5441)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by jugrajsingh** [comment]
Check Now.
I think the error is fixed now.

**Comment by jugrajsingh** [comment]
I have Updated the Code
Change Map from google map to OSM
Now Please resolve the EditAccountActivity.java conflict and merge the code.
Note: No API Key Required

**Comment by jugrajsingh** [comment]
You May have to manually give the Storage permission is previously not given to make the OSM map work.

**Comment by amarjeetkapoor1** [comment]
Unable to see OSM map on building

**Comment by jugrajsingh** [comment]
What building?
Did you give storage permission manually.
Also check all permissions are given and Did OSM map appearing in the activity?

**Pull request merged**
